### ISSUE TITLE
scala 类型参数，类型约束 报错

### ISSUE THREAD

**Issue by thinktothings** [harlixxy/x-x-x#1]
/*\* 
- 代码
- scala 类型参数，类型约束 报错
- corresponds方法检查两个序列是否有相互对应的条目
  */

def corresponds[B](that:Seq[B])(match: (A,B) => Boolean):Boolean

/**
*报错信息
*/
Error:(48, 38) Wrong top statement declaration

**Comment by harlixxy** [comment]
查看下def 定义语法。
错误相关描述：
1. A类型未定义
2. B是泛型，加中括号
3. match ： 关键字，改名
4. def需要定义实体，也就是要添加函数体
类似语句：
scala> def corresponds[A,B](a:%28A,B%29 => Boolean):Boolean = true
corresponds: [A, B](a: %28A, B%29 => Boolean)Boolean
