### ISSUE TITLE
persist与checkpoint作用？

### ISSUE THREAD

**Issue by xuzhiliang** [harlixxy/x-x-x#10]
情景：一个stage 持久化persist或ckeckpoint，
1）persist是把这个stage的依赖关系缓存起来，下次也还是要从头计算数据的，只是节省了组织依赖关系的时间；
2）checkpoint是把这个stage的计算结果写到硬盘，下歌stage直接从这个结果开始往后计算，不用从头计算这个stage的数据了！
我这样理解对不？？？

**Comment by cxljkb1994** [comment]
持久化：
可以用persist()或cache()方法来标记一个要被持久化的RDD，然后一旦首次被一个动作（Action）触发计算，它将会被保留在计算结点的内存中并重用。Cache有容错机制，如果RDD的任一分区丢失了，通过使用原先创建它的转换操作，它将会被自动重算（不需要全部重算，只计算丢失的部分）。当需要删除被持久化的RDD，可以用unpersistRDD()来完成该工作。此外，每一个RDD都可以用不同的保存级别进行保存，从而允许你持久化数据集在硬盘，或者在内存作为序列化的Java对象（节省空间），甚至于跨结点复制。这些等级选择，是通过将一个rg.apache.spark.storage.StorageLevel对象传递给persist()方法进行确定。cache()方法是使用默认存储级别的快捷方法，也就是torageLevel.MEMORY_ONLY(将反序列化的对象存入内存）。
ckeckpoint：
虽然缓存好用，可以满足大多数情况下的RDD的计算，但是缓存会存在丢失的情况，(对于计算复杂或者长链条)，重新计算带来性能的开销，具体在于检查点被触发之后，重新开启一个JOB开始工作

**Comment by xuzhiliang** [comment]
persist的存储级别为DISK_ONLY，作用岂不是跟ckeckpoint一样？现在有疑问的是persist缓存的内容是什么？依赖关系or中间数据？

**Comment by cxljkb1994** [comment]
checkpoint不仅仅做了将数据保存在本地磁盘，同时此RDD所依赖的所有父RDD的依赖关系都会被移除，当成一个新的Job处理

**Comment by xuzhiliang** [comment]
后面的问题呢？

**Comment by cxljkb1994** [comment]
没怎么理解你的后面的问题的意思

**Comment by xuzhiliang** [comment]
那我换个问法，persist是不是把计算结果缓存起来，下次计算就不用重头开始算，直接用？

**Comment by cxljkb1994** [comment]
对的，数据可以直接从缓存中调用

**Comment by xuzhiliang** [comment]
以前认为persist不缓存结果呢，现在大概懂了，作用还是跟ckeckpoint差不多，但还是有点区别的

**Comment by cxljkb1994** [comment]
https://github.com/JerryLead/SparkInternals/blob/master/markdown/6-CacheAndCheckpoint.md
这个里面有更加详细的内容，从功能看，两者差不多
