### ISSUE TITLE
spark-maven-安装报错

### ISSUE THREAD

**Issue by thinktothings** [harlixxy/x-x-x#2]
需求：运行wordCount报错，环境，是scala工程增加maven，直接在intellij中运行类wordCount2.scala报错

1.新建 scala项目，增加maven的支持
2.pom.xml配置如下
3.直接运行net.yiup.modules.common.bigdata.spark.quickstart.WordCount_2.scala 报错（如下）
4.错误信息如下
5.此示例参考资 料

---
## 错误信息如下

Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;
    at org.apache.spark.util.Utils$.getSystemProperties(Utils.scala:1546)
    at org.apache.spark.SparkConf.<init>(SparkConf.scala:59)
    at org.apache.spark.SparkConf.<init>(SparkConf.scala:53)
    at net.yiup.modules.common.bigdata.spark.quickstart.WordCount_2$delayedInit$body.apply(WordCount_2.scala:9)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
    at scala.App$class.main(App.scala:71)
    at net.yiup.modules.common.bigdata.spark.quickstart.WordCount_2$.main(WordCount_2.scala:8)
    at net.yiup.modules.common.bigdata.spark.quickstart.WordCount_2.main(WordCount_2.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.inte

---
## WordCount_2.scala

package net.yiup.modules.common.bigdata.spark.quickstart

import org.apache.spark.{SparkContext, SparkConf}

object WordCount_2 extends App{
  val conf = new SparkConf()
  conf.setAppName("单词计数2")
  //conf.setMaster("local")
  conf.setMaster("spark://S20:7077")
  conf.setJars(Array("/Users/hadoop/workspace/bigdata/all_frame_intellij/Spark1.6.0.-practice-maven/target/Spark1.6.0-practice-maven-1.0.jar"))
  val sc = new SparkContext(conf)
  val textFile = sc.textFile("hdfs://S20:9000/library/wordcount/input/Data/wordCount.txt",1)
  val counts = textFile.flatMap(line => line.split(" ")).map(word => (word,1)).reduceByKey(_ + _)
  counts.saveAsTextFile("hdfs://S20:9000/library/wordcount/output/spark_word_count_7")

}

---
## pom.xml

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

```
<groupId>yjmyzz</groupId>
<artifactId>${project.name}</artifactId>
<version>1.0</version>

<dependencies>
```

```
    <dependency>
        <groupId>log4j</groupId>
        <artifactId>log4j</artifactId>
        <version>1.2.12</version>
    </dependency>
    <dependency>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-core_2.11</artifactId>
        <version>${apache.spark-core.version}</version>
    </dependency>
    <dependency>
        <groupId>org.apache.hadoop</groupId>
        <artifactId>hadoop-client</artifactId>
        <version>${apache.hadoop-client.version}</version>
    </dependency>


</dependencies>

<build>
    <plugins>
        <plugin>
            <groupId>org.scala-tools</groupId>
            <artifactId>maven-scala-plugin</artifactId>
            <version>2.15.2</version>
            <executions>
                <execution>
                    <goals>
                        <goal>compile</goal>
                        <goal>testCompile</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
<properties>
    <project.name>Spark1.6.0-practice-maven</project.name>
    <scala.version>2.10.6</scala.version>
    <apache.hadoop-client.version>2.6.0</apache.hadoop-client.version>
    <apache.spark-core.version>1.6.0</apache.spark-core.version>
</properties>
```

</project>

---
## 示例参考资料

Spark 1.6.0 uses Scala 2.10. To write applications in Scala, you will need to use a compatible Scala version (e.g. 2.10.X).

To write a Spark application, you need to add a Maven dependency on Spark. Spark is available through Maven Central at:

groupId = org.apache.spark
artifactId = spark-core_2.10
version = 1.6.0
In addition, if you wish to access an HDFS cluster, you need to add a dependency on hadoop-client for your version of HDFS.

groupId = org.apache.hadoop
artifactId = hadoop-client
version = <your-hdfs-version>
Finally, you need to import some Spark classes into your program. Add the following lines:

**Comment by harlixxy** [comment]
1.  报错信息与Scala有关，如类型不能转换，方法找不到等等，先检查下，编译对象依赖的Scala版本，有以下两种可能：
   a)  运行环境的scala版本与编译时使用的版本不一致
   b)  引进的依赖包，如scalatest等，编译时的scala版本与运行时的版本不一致。
   错误信息如：
2.  java.lang.ClassCastException
3.  Exception in thread "main" java.lang.NoSuchMethodError: scala.collection.immutable.HashSet$.empty()Lscala/collection/immutable/HashSet 

根本原因：scala是向前兼容，却不支持向后兼容
参考：http://www.scala-lang.org/node/11466

**Comment by harlixxy** [comment]
<dependency>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-core_2.11</artifactId>
        <version>${apache.spark-core.version}</version>
    </dependency>

依赖中spark-core_2.11，后面的2.11表示使用的scala版本，和参考资料描述的使用2.10不同。
相关的类似错误 信息，参考前面的说明，检查scala版本是否一致。

**Comment by harlixxy** [comment]
补充资料： https://github.com/harlixxy/StudyNotes/ 的根目录下，spark学习笔记 —— 34.10    运行时报错章节
