### ISSUE TITLE
ERROR util.SparkUncaughtExceptionHandler

### ISSUE THREAD

**Issue by wbshanghai** [harlixxy/x-x-x#4]
ERROR util.SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[appclient-registration-retry-thread,5,main]
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@542f7b0d rejected from java.util.concurrent.ThreadPoolExecutor@3dff47b4[Running, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
在集群中运行WordCount.jar 中的 WordCount_Cluster 时出现的异常
希望王老师能帮忙分析一下，这个异常出现的原因及，及如何破解？

**Comment by harlixxy** [comment]
ERROR util.SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[appclient-registration-retry-thread,5,main]

appclient-registration-retry-thread ： 对应为应用程序注册到Master失败，检查下网络连接、集群环境是否正常，还有指定的master  url是否正确。
