### ISSUE TITLE
广告点击排名产生两个job？

### ISSUE THREAD

**Issue by xuzhiliang** [harlixxy/x-x-x#9]
1.代码
val lines = sc.textFile("/test").flatMap(_.split(" ")).map((_,1)).reduceByKey(_+_).map(x=>(x._2,x._2)).sortByKey(false).map(x=>(x._2,x._1)).collect

2.界面截图
![image](https://cloud.githubusercontent.com/assets/7847537/12637273/dd84d722-c5ce-11e5-81c7-9dc7be30aaf8.png)

为什么会产生一个sortByKey的job？？

**Comment by harlixxy** [comment]
1.  Job的触发条件
   Job 是由Action触发的，当Driver Program需要获取执行的结果时（类似于collect等等需要返回某个执行结果到Driver端），就会触发一个Job的执行 —— 这也是Transformation和Action的区别 。
2. 从Job触发条件推断、查阅源码的可能操作
   从上面的分析，可以猜测在sortByKey中，肯定调用了一个Action操作，获取了某个执行结果，查看代码：
   val part = new RangePartitioner(numPartitions, self, ascending)
   new ShuffledRDD[K, V, V](self, part)
     .setKeyOrdering(if (ascending) ordering else ordering.reverse)

第二步是构建ＲＤＤ，因此对应在第一步中，对应为构建一个根据范围进行分区的分区器　——　这时候需要有一个范围的信息　——　对应在RangePartitioner类中有范围信息对应的变量，rangeBounds，该变量的计算过程中，使用了Action操作，代码如下：
private var rangeBounds: Array[K] = {
......
         val imbalanced = new PartitionPruningRDD(rdd.map(_._1), imbalancedPartitions.contains)
          val seed = byteswap32(-rdd.id - 1)
          val reSampled = imbalanced.sample(withReplacement = false, fraction, seed)**.collect()**

.......

注意，这里的collect()操作，就是一种Action，需要获取执行结果，这时候会触发一个Job，原理就是前面描述的 ——上面是通过原理去推导源码的过程。
